### ISSUE TITLE
Fatal error: Arguments to path.resolve must be strings

### ISSUE THREAD

**Issue by josephspens** [sindresorhus/grunt-sass#203]
- grunt-sass v0.18.1
- node-sass v2.1.1
- node v0.12.0

I apologize if this is a duplicate issue and/or answered elsewhere, I checked around grunt-sass issues, node-sass issues, and grunt-notify without finding this error message discussed anywhere. Also I hope this is the place to report the issue and not node-sass.

When running `grunt sass:prod`
```bash
    Running "sass:prod" (sass) task
    Verifying property sass.prod exists in config...OK
    Files: src/main/webapp/media/styles/app.scss -> src/main/webapp/media/cache/app.css
    Files: src/main/webapp/media/styles/core.scss -> src/main/webapp/media/cache/core.css
    Options: precision=10, sourceMap, update, includePaths=["src/main/webapp/media/bower_components"], style="compressed"
    Options: precision=10, sourceMap, update, includePaths=["src/main/webapp/media/bower_components"], style="compressed"
    >> [grunt-notify] growl: growlnotify wasn't found. If you were hoping to use Growl, make you sure you have their command line script called Growlnotify. Mac: http://growl.info/downloads or Windows: http://www.growlforwindows.com/gfw/help/growlnotify.aspx and put it in your path. You should be able to type growlnotify --version and get something back.
    >> [grunt-notify] IS_WINDOWS: false
    >> [grunt-notify] PROGRAM_FILES: undefined
    >> [grunt-notify] PROGRAM_FILES_X86: undefined
    >> [grunt-notify] fullPathToApplication: false
    >> [grunt-notify] snarl: Snarl not available for this OS.
    >> [grunt-notify] os: Darwin
    >> [grunt-notify] version: 14.1.0
    >> [grunt-notify] IS_MAC: true
    >> [grunt-notify] MOUNTAIN_LION: true
    >> [grunt-notify] notification_center: Will use Notification Center
    >> [notification-center] cmd: /Users/joseph/Development/work-market/application/node_modules/grunt-notify/bin/Grunt.app/Contents/MacOS/Grunt
    >> [notification-center] args: -title backend sass:prod -message Arguments to path.resolve must be strings
    Fatal error: Arguments to path.resolve must be strings
```
Gruntfile:
```javascript
sass: {
	options: {
		sourceMap: true,
		update: true,
		includePaths: ['<%= yeoman.components %>']
	},
	prod: {
		options: {
			style: 'compressed'
		},
		files: {
			'<%= yeoman.cache %>/app.css': '<%= yeoman.styles %>/app.scss',
			'<%= yeoman.cache %>/core.css': '<%= yeoman.styles %>/core.scss'
		}
	},
}
```
I've cleared out my `node_modules`, and reinstalled everything. I'm able to run the task if I downgrade to these versions:
- grunt-sass v0.17.x
- node-sass v1.x.x
- node v0.10.36

I've instructed my team to _not_ upgrade to node v0.12, however we're onboarding a lot of people and they're all downloading the latest package versions, so ideally we want our setup to work with node 0.12 out of the box.

**Comment by sindresorhus** [comment]
Try the latest alpha and see if that solves it for you: https://github.com/sindresorhus/grunt-sass/issues/196#issuecomment-87578544

**Comment by josephspens** [comment]
On node v0.12.0,
node-sass v3.0.0-beta.5,
grunt-sass 0.18.1

```bash
Loading "sass.js" tasks...ERROR
>> Error: `libsass` bindings not found. Try reinstalling `node-sass`?

Running "concurrent:dev" (concurrent) task
    Warning: Loading "sass.js" tasks...ERROR
    >> Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    Warning: Task "sass:dev" not found. Use --force to continue.
    
    Aborted due to warnings.
    
    
    Execution Time (2015-04-06 16:09:38 UTC)
    loading tasks  362ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
    Total 362ms Use --force to continue.
        
        Aborted due to warnings.
    

Execution Time (2015-04-06 16:09:36 UTC)
loading tasks   248ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 11%
concurrent:dev   2.1s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 89%
Total 2.3s
``` 
I did an npm cache clean and install before doing this.

**Comment by am11** [comment]
Hello,

Please make a gist for output of this:
https://gist.github.com/am11/9f429c211822a9b15aee replacing `npm install node-sass` with `npm install node-sass@beta`.

Also, which version of MacOS you are using?

//cc @xzyfer

**Comment by josephspens** [comment]
@am11 Thanks for responding, I'm running Yosemite
https://gist.github.com/josephspens/4eeb8176a669ff64f25b

```Shell
2.3.0
v0.12.0
{ http_parser: '2.3',
  node: '0.12.0',
  v8: '3.28.73',
  uv: '1.0.2',
  zlib: '1.2.8',
  modules: '14',
  openssl: '1.0.1l' }
darwin
x64
/
> node-sass@3.0.0-beta.5 install /Users/joseph/temp1/node_modules/node-sass
> node scripts/install.js
 
Binary downloaded and installed at /Users/joseph/temp1/node_modules/node-sass/vendor/darwin-x64-14/binding.node
 
> node-sass@3.0.0-beta.5 postinstall /Users/joseph/temp1/node_modules/node-sass
> node scripts/build.js
 
` /Users/joseph/temp1/node_modules/node-sass/vendor/darwin-x64-14/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.
node-sass@3.0.0-beta.5 node_modules/node-sass
├── get-stdin@4.0.1
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── nan@1.7.0
├── meow@3.1.0 (object-assign@2.0.0, camelcase-keys@1.0.0, minimist@1.1.1, indent-string@1.2.1)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── npmconf@2.1.1 (uid-number@0.0.5, inherits@2.0.1, osenv@0.1.0, ini@1.3.3, once@1.3.1, nopt@3.0.1, config-chain@1.1.8, semver@4.3.3)
├── gaze@0.5.1 (globule@0.1.0)
├── request@2.55.0 (caseless@0.9.0, json-stringify-safe@5.0.0, aws-sign2@0.5.0, forever-agent@0.6.0, stringstream@0.0.4, oauth-sign@0.6.0, tunnel-agent@0.4.0, isstream@0.1.2, node-uuid@1.4.3, qs@2.4.1, combined-stream@0.0.7, form-data@0.2.0, mime-types@2.0.10, http-signature@0.10.1, bl@0.9.4, tough-cookie@0.12.1, hawk@2.3.1, har-validator@1.6.1)
├── sass-graph@1.2.0 (commander@2.7.1, glob@4.5.3, lodash@2.4.1)
└── pangyp@2.1.0 (which@1.0.9, osenv@0.1.0, rimraf@2.2.8, graceful-fs@3.0.6, nopt@3.0.1, glob@4.3.5, semver@4.2.2, fstream@1.0.4, minimatch@2.0.4, tar@1.0.3, npmlog@1.0.0, request@2.51.0)
node-sass	3.0.0-beta.5	(Wrapper)	[JavaScript]
libsass  	3.2.0-beta.5	(Sass Compiler)	[C/C++]
[eval]:1
console.log(require('node-sass').info())
                                 ^
TypeError: string is not a function
    at [eval]:1:34
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)
    at startup (node.js:90:7)
    at node.js:814:3
node-sass	3.0.0-beta.5	(Wrapper)	[JavaScript]
libsass  	3.2.0-beta.5	(Sass Compiler)	[C/C++]
undefined
node-sass	3.0.0-beta.5	(Wrapper)	[JavaScript]
libsass  	3.2.0-beta.5	(Sass Compiler)	[C/C++]
undefined
```

**Comment by am11** [comment]
It seems it is working fine, when installed separately. 

Now we need to figure out why it is throwing `\`libsass\` binding not found` when install via grunt-sass.

Can you try installing grunt-sass alpha in `~/temp` (isolated mode)?

**Comment by josephspens** [comment]
Not sure what isolated mode is... when installing grunt-sass (after running the script above, and without deleting the temp directory) I get this output
```Bash
joseph-> npm install grunt-sass
|
> node-sass@2.1.1 install /Users/joseph/temp1/node_modules/grunt-sass/node_modules/node-sass
> node scripts/install.js


> node-sass@2.1.1 postinstall /Users/joseph/temp1/node_modules/grunt-sass/node_modules/node-sass
> node scripts/build.js

`darwin-x64-node-0.12` exists; testing
Binary is fine; exiting
grunt-sass@0.18.1 node_modules/grunt-sass
├── object-assign@2.0.0
├── each-async@1.1.1 (set-immediate-shim@1.0.1, onetime@1.0.0)
└── node-sass@2.1.1 (get-stdin@4.0.1, replace-ext@0.0.1, cross-spawn@0.2.8, nan@1.7.0, chalk@0.5.1, mkdirp@0.5.0, semver@4.3.3, shelljs@0.3.0, meow@3.1.0, npmconf@2.1.1, gaze@0.5.1, sass-graph@1.2.0, request@2.55.0, mocha@2.2.1, pangyp@2.1.0)
```

**Comment by am11** [comment]
> Not sure what isolated mode is

I meant in temp directory by running `npm install --save-dev sindresorhus/grunt-sass`.

**Comment by josephspens** [comment]
Like this?
```Bash
joseph-> npm cache clean && npm install --save-dev sindresorhus/grunt-sass
grunt-sass@0.18.1 node_modules/grunt-sass
├── object-assign@2.0.0
└── each-async@1.1.1 (set-immediate-shim@1.0.1, onetime@1.0.0)
```

**Comment by am11** [comment]
Yup.
I would give it a clean attempt (because you already installed node-sass@beta separately) like so:

```bash
cd /tmp
rm -rf node_modules
npm install --save-dev sindresorhus/grunt-sass

# now test with real code, if it is actually compiling files
```

If the above works, that naturally means both node-sass and grunt-sass are doing what they are supposed to do. :)

**Comment by josephspens** [comment]
I noticed I included node-sass in my project's package.json, so I removed that line + deleted my entire node_modules directory, ran `npm install --save-dev sindresorhus/grunt-sass` and npm install (to grab grunt and whatnot). After running `grunt sass:dev -v` I got the following output
```bash
Running "sass:dev" (sass) task
Verifying property sass.dev exists in config...OK
Files: src/main/webapp/media/styles/app.scss -> src/main/webapp/media/cache/app.css
Options: precision=10, sourceMap, update, includePaths=["src/main/webapp/media/bower_components"], style="expanded"
Bus error: 10
```
I googled around and apparently the solution to the bus error is to "upgrade" node to 0.10.22... obviously they're old threads.

Did you intend for me to build a new project to test the sass compilation in the `tmp` directory?

**Comment by am11** [comment]
There are two issues you reported. 

The first one (`path.resolve`) is a partly node-sass bug and partly "by design". I will fix the node-sass bug, but it will only stop emitting error and you will not get sourceMap in response because the pre-requisite of having source-map is to set `outFile` option (as mentioned in node-sass' readme). You can open this bug report in node-sass repo so it does not get forgotten. Besides, I am not sure why destination `outFile` is not set by grunt-sass in your case.

The second issue is installation; <code>\`libsass\` binding not found</code>. Sometimes it happens due to network issue or timeout/hungups (some external factor). Isolating the installation process renders a clear picture whether or not it is the issue with package. When node-sass installs, it downloads the prebuild binary (library; matching the description of your environment) separately, right after the npm finishes its install routine. If there is a network issue at that very instance, you will probably get that error. Apparently that is what happened when you first tried node-sass v3.0.0-beta.5.

**Comment by am11** [comment]
Cross referencing https://github.com/sass/node-sass/issues/839.

**Comment by xzyfer** [comment]
node-sass@3.0.0-beta.7 has been released.

**Comment by xzyfer** [comment]
@josephspens please try the instructions from https://github.com/sindresorhus/grunt-sass/issues/203#issuecomment-90156951 and confirm the problem still exists.

**Comment by josephspens** [comment]
Sorry it took a minute, got swamped at work.

Here's the output after downloading the latest beta version:

```bash
mkdir: /Users/joseph/temp1: File exists
2.3.0
v0.12.0
{ http_parser: '2.3',
  node: '0.12.0',
  v8: '3.28.73',
  uv: '1.0.2',
  zlib: '1.2.8',
  modules: '14',
  openssl: '1.0.1l' }
darwin
x64
-
> node-sass@3.0.0-beta.7 install /Users/joseph/temp1/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Users/joseph/temp1/node_modules/node-sass/vendor/darwin-x64-14/binding.node

> node-sass@3.0.0-beta.7 postinstall /Users/joseph/temp1/node_modules/node-sass
> node scripts/build.js

` /Users/joseph/temp1/node_modules/node-sass/vendor/darwin-x64-14/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.
node-sass@3.0.0-beta.7 node_modules/node-sass
├── get-stdin@4.0.1
├── async-foreach@0.1.3
├── nan@1.7.0
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── meow@3.1.0 (object-assign@2.0.0, camelcase-keys@1.0.0, minimist@1.1.1, indent-string@1.2.1)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── glob@5.0.5 (path-is-absolute@1.0.0, inherits@2.0.1, inflight@1.0.4, once@1.3.1, minimatch@2.0.4)
├── npmconf@2.1.1 (uid-number@0.0.5, inherits@2.0.1, osenv@0.1.0, ini@1.3.3, once@1.3.1, nopt@3.0.1, config-chain@1.1.8, semver@4.3.3)
├── gaze@0.5.1 (globule@0.1.0)
├── request@2.55.0 (caseless@0.9.0, json-stringify-safe@5.0.0, aws-sign2@0.5.0, forever-agent@0.6.1, stringstream@0.0.4, oauth-sign@0.6.0, tunnel-agent@0.4.0, isstream@0.1.2, node-uuid@1.4.3, qs@2.4.1, combined-stream@0.0.7, form-data@0.2.0, mime-types@2.0.10, http-signature@0.10.1, bl@0.9.4, tough-cookie@0.13.0, hawk@2.3.1, har-validator@1.6.1)
├── sass-graph@1.3.0 (commander@2.8.0, glob@4.5.3, lodash@2.4.1)
└── pangyp@2.1.0 (which@1.0.9, osenv@0.1.0, rimraf@2.2.8, graceful-fs@3.0.6, nopt@3.0.1, glob@4.3.5, fstream@1.0.4, semver@4.2.2, minimatch@2.0.4, tar@1.0.3, npmlog@1.0.0, request@2.51.0)
node-sass	3.0.0-beta.7	(Wrapper)	[JavaScript]
libsass  	3.2.0-beta.6	(Sass Compiler)	[C/C++]
[eval]:1
console.log(require('node-sass').info())
                                 ^
TypeError: string is not a function
    at [eval]:1:34
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)
    at startup (node.js:90:7)
    at node.js:814:3
node-sass	3.0.0-beta.7	(Wrapper)	[JavaScript]
libsass  	3.2.0-beta.6	(Sass Compiler)	[C/C++]
undefined
node-sass	3.0.0-beta.7	(Wrapper)	[JavaScript]
libsass  	3.2.0-beta.6	(Sass Compiler)	[C/C++]
undefined
```

**Comment by xzyfer** [comment]
@josephspens due to an api change `info` is now an object not a function. That's what this error is telling you.

```js
console.log(require('node-sass').info)
```

**Comment by xzyfer** [comment]
@josephspens the crux of this issue appears to be simply that you are using an incompatible version of node-sass. Grunt-sass@0.18.1 is designed for node-sass@2.x. If you need node-sass@3.x you'll need to use master.

**Comment by josephspens** [comment]
I don't care what version of node-sass or grunt-sass I'm using, I just want this to work on node 0.12.

Which versions should I be using?
grunt-sass 0.17 and node-sass 2.x?

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/grunt-sass/issues/196#issuecomment-87578544

**Comment by josephspens** [comment]
After reading the comment posted above, I decided to try using master branches for both node-sass and grunt-sass

- node 0.12.0
- grunt-sass 0.18.1 (master)
- node-sass 3.0.0-beta.7 (master)

Running `grunt sass:dev -v`
```shell
Registering "grunt-sass" local Npm module tasks.
Reading /Users/joseph/Development/work-market/application/node_modules/grunt-sass/package.json...OK
Parsing /Users/joseph/Development/work-market/application/node_modules/grunt-sass/package.json...OK

node-sass	3.0.0-beta.7	(Wrapper)	[JavaScript]
libsass  	3.2.0-beta.6	(Sass Compiler)	[C/C++]

Loading "sass.js" tasks...OK
+ sass
Initializing config...OK
Loading "Gruntfile.js" tasks...OK
+ build, default, local, serve, test

Running tasks: sass:dev

Running "sass:dev" (sass) task
Verifying property sass.dev exists in config...OK
Files: src/main/webapp/media/styles/_config.scss -> src/main/webapp/media/cache/_config.css
Files: src/main/webapp/media/styles/_legacy.scss -> src/main/webapp/media/cache/_legacy.css
Files: src/main/webapp/media/styles/_states.scss -> src/main/webapp/media/cache/_states.css
Files: src/main/webapp/media/styles/app.scss -> src/main/webapp/media/cache/app.css
Files: src/main/webapp/media/styles/core.scss -> src/main/webapp/media/cache/core.css
Files: src/main/webapp/media/styles/wysiwyg.scss -> src/main/webapp/media/cache/wysiwyg.css
Options: precision=10, sourceMap, update, includePaths=["src/main/webapp/media/bower_components"], style="expanded"
Options: precision=10, sourceMap, update, includePaths=["src/main/webapp/media/bower_components"], style="expanded"
Options: precision=10, sourceMap, update, includePaths=["src/main/webapp/media/bower_components"], style="expanded"
Options: precision=10, sourceMap, update, includePaths=["src/main/webapp/media/bower_components"], style="expanded"
Options: precision=10, sourceMap, update, includePaths=["src/main/webapp/media/bower_components"], style="expanded"
Options: precision=10, sourceMap, update, includePaths=["src/main/webapp/media/bower_components"], style="expanded"
Writing src/main/webapp/media/cache/wysiwyg.css...OK
Writing /Users/joseph/Development/work-market/application/src/main/webapp/media/cache/wysiwyg.css.map...OK
Bus error: 10
```

Tried again with latest release versions on node 0.12:

- node 0.12.0
- grunt-sass 0.18.1
- node-sass 2.1.1

Running `grunt sass:dev -v`
```shell
Registering "grunt-sass" local Npm module tasks.
Reading /Users/joseph/Development/work-market/application/node_modules/grunt-sass/package.json...OK
Parsing /Users/joseph/Development/work-market/application/node_modules/grunt-sass/package.json...OK

node-sass version: 2.1.1
libsass version: 3.1.0

Loading "sass.js" tasks...OK
+ sass
Initializing config...OK
Loading "Gruntfile.js" tasks...OK
+ build, default, local, serve, test

Running tasks: sass:dev

Running "sass:dev" (sass) task
Verifying property sass.dev exists in config...OK
Files: src/main/webapp/media/styles/_config.scss -> src/main/webapp/media/cache/_config.css
Files: src/main/webapp/media/styles/_legacy.scss -> src/main/webapp/media/cache/_legacy.css
Files: src/main/webapp/media/styles/_states.scss -> src/main/webapp/media/cache/_states.css
Files: src/main/webapp/media/styles/app.scss -> src/main/webapp/media/cache/app.css
Files: src/main/webapp/media/styles/core.scss -> src/main/webapp/media/cache/core.css
Files: src/main/webapp/media/styles/wysiwyg.scss -> src/main/webapp/media/cache/wysiwyg.css
Options: precision=10, sourceMap, update, includePaths=["src/main/webapp/media/bower_components"], style="expanded"
Options: precision=10, sourceMap, update, includePaths=["src/main/webapp/media/bower_components"], style="expanded"
Options: precision=10, sourceMap, update, includePaths=["src/main/webapp/media/bower_components"], style="expanded"
Options: precision=10, sourceMap, update, includePaths=["src/main/webapp/media/bower_components"], style="expanded"
Options: precision=10, sourceMap, update, includePaths=["src/main/webapp/media/bower_components"], style="expanded"
Options: precision=10, sourceMap, update, includePaths=["src/main/webapp/media/bower_components"], style="expanded"
Writing src/main/webapp/media/cache/wysiwyg.css...OK
Writing src/main/webapp/media/cache/wysiwyg.css.map...OK
>> [grunt-notify] growl: growlnotify wasn't found. If you were hoping to use Growl, make you sure you have their command line script called Growlnotify. Mac: http://growl.info/downloads or Windows: http://www.growlforwindows.com/gfw/help/growlnotify.aspx and put it in your path. You should be able to type growlnotify --version and get something back.
>> [grunt-notify] IS_WINDOWS: false
>> [grunt-notify] PROGRAM_FILES: undefined
>> [grunt-notify] PROGRAM_FILES_X86: undefined
>> [grunt-notify] fullPathToApplication: false
>> [grunt-notify] snarl: Snarl not available for this OS.
>> [grunt-notify] os: Darwin
>> [grunt-notify] version: 14.1.0
>> [grunt-notify] IS_MAC: true
>> [grunt-notify] MOUNTAIN_LION: true
>> [grunt-notify] notification_center: Will use Notification Center
>> [notification-center] cmd: /Users/joseph/Development/work-market/application/node_modules/grunt-notify/bin/Grunt.app/Contents/MacOS/Grunt
>> [notification-center] args: -title backend sass:dev -message Arguments to path.resolve must be strings
Fatal error: Arguments to path.resolve must be strings


Execution Time (2015-04-23 16:59:03 UTC)
loading tasks  258ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 63%
sass:dev       153ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 37%
Total 412ms
```

Same output using the same packages but downgrading to node 0.10.36:

- node 0.10.36
- grunt-sass 0.18.1
- node-sass 2.1.1

Running `grunt sass:dev -v`
```shell
Registering "grunt-sass" local Npm module tasks.
Reading /Users/joseph/Development/work-market/application/node_modules/grunt-sass/package.json...OK
Parsing /Users/joseph/Development/work-market/application/node_modules/grunt-sass/package.json...OK

node-sass version: 2.1.1
libsass version: 3.1.0

Loading "sass.js" tasks...OK
+ sass
Initializing config...OK
Loading "Gruntfile.js" tasks...OK
+ build, default, local, serve, test

Running tasks: sass:dev

Running "sass:dev" (sass) task
Verifying property sass.dev exists in config...OK
Files: src/main/webapp/media/styles/_config.scss -> src/main/webapp/media/cache/_config.css
Files: src/main/webapp/media/styles/_legacy.scss -> src/main/webapp/media/cache/_legacy.css
Files: src/main/webapp/media/styles/_states.scss -> src/main/webapp/media/cache/_states.css
Files: src/main/webapp/media/styles/app.scss -> src/main/webapp/media/cache/app.css
Files: src/main/webapp/media/styles/core.scss -> src/main/webapp/media/cache/core.css
Files: src/main/webapp/media/styles/wysiwyg.scss -> src/main/webapp/media/cache/wysiwyg.css
Options: precision=10, sourceMap, update, includePaths=["src/main/webapp/media/bower_components"], style="expanded"
Options: precision=10, sourceMap, update, includePaths=["src/main/webapp/media/bower_components"], style="expanded"
Options: precision=10, sourceMap, update, includePaths=["src/main/webapp/media/bower_components"], style="expanded"
Options: precision=10, sourceMap, update, includePaths=["src/main/webapp/media/bower_components"], style="expanded"
Options: precision=10, sourceMap, update, includePaths=["src/main/webapp/media/bower_components"], style="expanded"
Options: precision=10, sourceMap, update, includePaths=["src/main/webapp/media/bower_components"], style="expanded"
Writing src/main/webapp/media/cache/wysiwyg.css...OK
Writing src/main/webapp/media/cache/wysiwyg.css.map...OK
>> [grunt-notify] growl: growlnotify wasn't found. If you were hoping to use Growl, make you sure you have their command line script called Growlnotify. Mac: http://growl.info/downloads or Windows: http://www.growlforwindows.com/gfw/help/growlnotify.aspx and put it in your path. You should be able to type growlnotify --version and get something back.
>> [grunt-notify] IS_WINDOWS: false
>> [grunt-notify] PROGRAM_FILES: undefined
>> [grunt-notify] PROGRAM_FILES_X86: undefined
>> [grunt-notify] fullPathToApplication: false
>> [grunt-notify] snarl: Snarl not available for this OS.
>> [grunt-notify] os: Darwin
>> [grunt-notify] version: 14.1.0
>> [grunt-notify] IS_MAC: true
>> [grunt-notify] MOUNTAIN_LION: true
>> [grunt-notify] notification_center: Will use Notification Center
>> [notification-center] cmd: /Users/joseph/Development/work-market/application/node_modules/grunt-notify/bin/Grunt.app/Contents/MacOS/Grunt
>> [notification-center] args: -title backend sass:dev -message Arguments to path.resolve must be strings
Fatal error: Arguments to path.resolve must be strings


Execution Time (2015-04-23 17:01:49 UTC)
loading tasks  209ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 60%
sass:dev       141ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 40%
Total 351ms
```

And finally, using the configuration we have in production now, which works:

- node 0.10.36
- grunt-sass 0.18.1
- node-sass 1.2.3

Running `grunt sass:dev -v`
```shell
Registering "grunt-sass" local Npm module tasks.
Reading /Users/joseph/Development/work-market/application/node_modules/grunt-sass/package.json...OK
Parsing /Users/joseph/Development/work-market/application/node_modules/grunt-sass/package.json...OK
Loading "sass.js" tasks...OK
+ sass
Initializing config...OK
Loading "Gruntfile.js" tasks...OK
+ build, default, local, serve, test

Running tasks: sass:dev

Running "sass:dev" (sass) task
Verifying property sass.dev exists in config...OK
Files: src/main/webapp/media/styles/_config.scss -> src/main/webapp/media/cache/_config.css
Files: src/main/webapp/media/styles/_legacy.scss -> src/main/webapp/media/cache/_legacy.css
Files: src/main/webapp/media/styles/_states.scss -> src/main/webapp/media/cache/_states.css
Files: src/main/webapp/media/styles/app.scss -> src/main/webapp/media/cache/app.css
Files: src/main/webapp/media/styles/core.scss -> src/main/webapp/media/cache/core.css
Files: src/main/webapp/media/styles/wysiwyg.scss -> src/main/webapp/media/cache/wysiwyg.css
Options: precision=10, sourceMap, update, includePaths=["src/main/webapp/media/bower_components"], style="expanded"
Options: precision=10, sourceMap, update, includePaths=["src/main/webapp/media/bower_components"], style="expanded"
Options: precision=10, sourceMap, update, includePaths=["src/main/webapp/media/bower_components"], style="expanded"
Options: precision=10, sourceMap, update, includePaths=["src/main/webapp/media/bower_components"], style="expanded"
Writing src/main/webapp/media/cache/app.css...OK
Options: precision=10, sourceMap, update, includePaths=["src/main/webapp/media/bower_components"], style="expanded"
Writing src/main/webapp/media/cache/core.css...OK
Options: precision=10, sourceMap, update, includePaths=["src/main/webapp/media/bower_components"], style="expanded"
File src/main/webapp/media/cache/wysiwyg.css created.
File src/main/webapp/media/cache/wysiwyg.css.map created.
File src/main/webapp/media/cache/core.css created.
File src/main/webapp/media/cache/core.css.map created.
File src/main/webapp/media/cache/app.css created.
File src/main/webapp/media/cache/app.css.map created.

Done, without errors.


Execution Time (2015-04-23 17:07:07 UTC)
loading tasks  223ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 48%
sass:dev       243ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 52%
Total 467ms
```

One last comment... my package.json file explicitly calls for grunt-sass 0.17.x, and it tries to download 0.17.0, however when I inspect the package.json in grunt-sass it says it's 0.18.1. This sounds like an issue with tagging, or maybe I'm missing something. I did an `npm cache clean` before installing and I'm still getting the mismatched versions.
```shell
joseph-> npm install
grunt-sass@0.17.0 node_modules/grunt-sass
├── object-assign@2.0.0
├── each-async@1.1.1 (onetime@1.0.0, set-immediate-shim@1.0.1)
└── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
```

I want to thank everyone here for taking the time to help me with this... if this ends up being a dead end it's not the end of the world, it just means my team won't be able to upgrade node (or node-sass it seems). That may be a concern in the near future, but hopefully by then more versions of these packages will have been released for node 0.12 support.
